const spicyFoods = [
    { 
        name: 'Spicy Chicken Curry', 
        price: 12.99, 
        scoville: 500, 
        meat: "Chicken",
        imglink: "../img/scc.jpg",
    },
    { 
        name: 'Sriracha Shrimp Stir-Fry', 
        price: 15.5, 
        scoville: 1000,
        meat: "Shrimp",
        imglink: "../img/srirachashrimp.jpg",
    },
    { 
        name: 'Jalapeno Popper Pizza', 
        price: 19.99, 
        scoville: 1500, 
        meat: "Beef",
        imglink: "../img/jalapenopizza.jpg",
    },
    {   
        name: 'Spicy Buffalo Wings', 
        price: 9.99, 
        scoville: 2000, 
        meat: "Chicken",
        imglink: "../img/buffalowings.jpg",
    },
    { 
        name: 'Ghost Pepper Tacos', 
        price: 10.99, 
        scoville: 5000, 
        meat: "Beef",
        imglink: "../img/ghostpeppertaco.webp",
    },
    { 
        name: 'Spicy Szechuan Noodles', 
        price: 13.5, 
        scoville: 8000, 
        meat: "Vegatarian",
        imglink: "../img/szechuannoodles.jpg",
    },
    { 
        name: 'Habanero BBQ Ribs', 
        price: 18.99, 
        scoville: 10000, 
        meat: "Beef",
        imglink: "../img/habaneroribs.jpg",
    },
    { 
        name: 'Thai Green Curry', 
        price: 14.99, 
        scoville: 12000, 
        meat: "Vegatarian",
        imglink: "../img/thaigreencurry.jpg",
    },
    { 
        name: 'Super Spicy Salsa', 
        price: 6.5, 
        scoville: 15000, 
        meat:"Vegatarian",
        imglink: "../img/spicysalsa.webp",
    },
    { 
        name: 'Carolina Reaper Burger', 
        price: 16.99, 
        scoville: 20000, 
        meat:"Beef",
        imglink: "../img/carolinaburger.png",
    },
    { 
        name: 'Spicy Kimchi Fried Rice', 
        price: 11.99, 
        scoville: 25000, 
        meat:"Vegatarian",
        imglink: "../img/kimchifriedrice.webp",
    },
    { 
        name: 'Scorpion Pepper Wings', 
        price: 9.5, 
        scoville: 30000,
        meat:"Chicken",
        imglink: "../img/scorpionwings.webp", 
    },
    { 
        name: 'Spicy Beef Vindaloo', 
        price: 13.99, 
        scoville: 35000, 
        meat:"Beef",
        imglink: "../img/beefvindaloo.jpg",
    },
    { 
        name: 'Tom Yum Soup', 
        price: 8.99, 
        scoville: 40000, 
        meat:"Shrimp",
        imglink: "../img/tomyum.jpg",
    },
    { 
        name: 'Spicy Cajun Jambalaya', 
        price: 21.99, 
        scoville: 50000, 
        meat:"Shrimp",
        imglink: "../img/spicyjambalaya.webp",
    },
  ];

export {spicyFoods};